name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build docker image
        run: docker build -t zobelle/dhbw-vorlesungsplan-frontend .

      - name: Save docker image to tar file
        run: docker save -o zobelle_dhbw-vorlesungsplan-frontend.tar zobelle/dhbw-vorlesungsplan-frontend

      - name: Copy docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "zobelle_dhbw-vorlesungsplan-frontend.tar"
          target: "dhbw-vorlesungsplan-frontend"

      - name: Load docker image and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd dhbw-vorlesungsplan-frontend
            docker load -i zobelle_dhbw-vorlesungsplan-frontend.tar
            docker-compose up -d
            rm zobelle_dhbw-vorlesungsplan-frontend.tar
